version: "3"

services:
    crypto:
        build: .
        environment:
            - FLAG=0123456789abcdefNCtfU{CbC_COol!}
        ports:
            - "10001:10001"
        restart: always
